# Generated by Django 4.2 on 2023-05-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
