# Generated by Django 4.2.1 on 2023-05-22 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import user.models
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Ism"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Familiya"
                    ),
                ),
                (
                    "avatar",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[400, 400],
                        upload_to="user_avatars/",
                        verbose_name="Rasim",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Pochta"
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "forget_password_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("last_login_time", models.DateTimeField(blank=True, null=True)),
                ("last_logout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Xodimlarning holati"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tug'ilgan kun"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=255,
                        null=True,
                        validators=[user.validators.phone_validator],
                        verbose_name="Telefon raqami",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("director", "Director"),
                            ("admin", "Admin"),
                            ("seller", "Soruvchi"),
                        ],
                        default="seller",
                        max_length=255,
                        verbose_name="Foydalanuvchi turi",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
            },
            managers=[
                ("objects", user.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ForgetPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forget_password_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
